INSERT INTO Cours (Id_Cours, Nom_Cours, Nombre_Seance) VALUES  (38072, 'Consectetuer libero tempor aptent ornare blandit malesuada dui.', 'Volutpat litora facilisis cras sagittis.');
INSERT INTO Cours (Id_Cours, Nom_Cours, Nombre_Seance) VALUES  (75038, 'Tristique magnis primis diam porta vivamus.', 'Accumsan hendrerit rhoncus quam lorem bibendum accumsan semper.');
INSERT INTO Cours (Id_Cours, Nom_Cours, Nombre_Seance) VALUES  (86876, 'Congue justo pulvinar ligula ante tristique id curabitur penatibus.', 'Morbi augue rhoncus nisi pharetra odio cras.');
INSERT INTO Cours (Id_Cours, Nom_Cours, Nombre_Seance) VALUES  (54545, 'Sit porttitor arcu dolor sed laoreet proin.', 'Lacinia class eleifend tempus pretium vehicula nibh condimentum rhoncus.');
INSERT INTO Cours (Id_Cours, Nom_Cours, Nombre_Seance) VALUES  (54545, 'Laoreet nonummy risus arcu venenatis parturient imperdiet ultricies mattis.', 'Dolor nibh habitant vivamus suscipit.');
INSERT INTO Cours (Id_Cours, Nom_Cours, Nombre_Seance) VALUES  (29760, 'Ad enim duis fusce aliquam curabitur.', 'Est at mus mollis aenean mus.');
INSERT INTO Cours (Id_Cours, Nom_Cours, Nombre_Seance) VALUES  (96601, 'Litora turpis dapibus cum elementum primis.', 'Magna nisi mauris ridiculus gravida justo.');
INSERT INTO Cours (Id_Cours, Nom_Cours, Nombre_Seance) VALUES  (38072, 'Cursus nibh ligula magna arcu tellus diam eros sagittis.', 'Primis mollis magnis suscipit sed lorem turpis dapibus convallis.');
INSERT INTO Cours (Id_Cours, Nom_Cours, Nombre_Seance) VALUES  (1161, 'Ultricies amet ligula conubia euismod.', 'Convallis tincidunt aliquet mollis nam dictum elit.');
INSERT INTO Cours (Id_Cours, Nom_Cours, Nombre_Seance) VALUES  (57889, 'Massa rhoncus fermentum fames netus ac etiam iaculis.', 'Convallis auctor venenatis nostra dignissim blandit tempus cum.');
INSERT INTO Cours (Id_Cours, Nom_Cours, Nombre_Seance) VALUES  (23753, 'Felis penatibus justo aenean ultricies nam.', 'Donec ullamcorper venenatis bibendum molestie imperdiet.');
INSERT INTO Cours (Id_Cours, Nom_Cours, Nombre_Seance) VALUES  (22578, 'Maecenas ut eros malesuada placerat vivamus sollicitudin facilisis velit.', 'Placerat semper volutpat metus non.');
INSERT INTO Cours (Id_Cours, Nom_Cours, Nombre_Seance) VALUES  (22578, 'Natoque curae; consectetuer class cras lacinia parturient.', 'Varius torquent nunc maecenas massa.');
INSERT INTO Cours (Id_Cours, Nom_Cours, Nombre_Seance) VALUES  (18645, 'Auctor massa eu ullamcorper primis turpis hendrerit arcu.', 'Dui sapien fusce fames molestie praesent accumsan tortor lorem.');
INSERT INTO Cours (Id_Cours, Nom_Cours, Nombre_Seance) VALUES  (75038, 'Magna turpis consequat tellus ac interdum viverra quam sagittis.', 'Quisque curae; mi cras consectetuer cursus malesuada velit.');
INSERT INTO Cours (Id_Cours, Nom_Cours, Nombre_Seance) VALUES  (54545, 'Vivamus curabitur sociis posuere aptent.', 'Urna eu nullam eu mollis semper magna vivamus lobortis.');
INSERT INTO Cours (Id_Cours, Nom_Cours, Nombre_Seance) VALUES  (75038, 'Quisque vel maecenas mi dignissim inceptos id phasellus.', 'Enim blandit porttitor est egestas facilisis sodales fringilla convallis.');
INSERT INTO Cours (Id_Cours, Nom_Cours, Nombre_Seance) VALUES  (38072, 'Molestie hymenaeos duis accumsan integer vel.', 'Scelerisque habitant hymenaeos purus ornare.');
INSERT INTO Cours (Id_Cours, Nom_Cours, Nombre_Seance) VALUES  (23753, 'Nam ad lacinia aenean tristique ligula mi.', 'Condimentum per at fames gravida.');
INSERT INTO Cours (Id_Cours, Nom_Cours, Nombre_Seance) VALUES  (22578, 'Sem convallis elementum sapien eros ullamcorper.', 'Fusce penatibus habitant purus per cum pretium curabitur.');
INSERT INTO Annee_Scolaire (Id_AnneeScolaire, Annee_Scolaire) VALUES  (1161, 'Id parturient cum sagittis massa cras dictum metus adipiscing.');
INSERT INTO Annee_Scolaire (Id_AnneeScolaire, Annee_Scolaire) VALUES  (75038, 'Parturient arcu fusce mauris morbi dictum.');
INSERT INTO Annee_Scolaire (Id_AnneeScolaire, Annee_Scolaire) VALUES  (20165, 'Taciti nam diam duis nec dolor euismod.');
INSERT INTO Annee_Scolaire (Id_AnneeScolaire, Annee_Scolaire) VALUES  (99640, 'Fames fringilla purus pretium integer scelerisque senectus pretium cum.');
INSERT INTO Annee_Scolaire (Id_AnneeScolaire, Annee_Scolaire) VALUES  (54545, 'Nunc curae; tristique ante mi luctus sapien mus.');
INSERT INTO Annee_Scolaire (Id_AnneeScolaire, Annee_Scolaire) VALUES  (92864, 'Magnis ornare sagittis ac parturient est id aptent.');
INSERT INTO Annee_Scolaire (Id_AnneeScolaire, Annee_Scolaire) VALUES  (1161, 'Suspendisse massa urna curae; ac nascetur.');
INSERT INTO Annee_Scolaire (Id_AnneeScolaire, Annee_Scolaire) VALUES  (99640, 'Curae; inceptos lobortis convallis facilisi.');
INSERT INTO Annee_Scolaire (Id_AnneeScolaire, Annee_Scolaire) VALUES  (22578, 'Sit ornare risus urna gravida.');
INSERT INTO Annee_Scolaire (Id_AnneeScolaire, Annee_Scolaire) VALUES  (86876, 'Malesuada cubilia enim semper gravida et feugiat sit cubilia.');
INSERT INTO Annee_Scolaire (Id_AnneeScolaire, Annee_Scolaire) VALUES  (1161, 'Pharetra urna nonummy etiam montes tellus pulvinar blandit egestas.');
INSERT INTO Annee_Scolaire (Id_AnneeScolaire, Annee_Scolaire) VALUES  (99640, 'Curabitur at suspendisse consequat aliquet semper vestibulum.');
INSERT INTO Annee_Scolaire (Id_AnneeScolaire, Annee_Scolaire) VALUES  (29760, 'Iaculis mollis natoque elementum magnis quam.');
INSERT INTO Annee_Scolaire (Id_AnneeScolaire, Annee_Scolaire) VALUES  (24535, 'Ridiculus ad rhoncus risus netus nisi eleifend imperdiet.');
INSERT INTO Annee_Scolaire (Id_AnneeScolaire, Annee_Scolaire) VALUES  (45161, 'Tortor hendrerit augue fermentum integer viverra ridiculus tortor diam.');
INSERT INTO Annee_Scolaire (Id_AnneeScolaire, Annee_Scolaire) VALUES  (54545, 'Varius nonummy elementum habitant aliquet curabitur.');
INSERT INTO Annee_Scolaire (Id_AnneeScolaire, Annee_Scolaire) VALUES  (92864, 'Posuere porttitor justo ultricies ipsum erat aptent metus.');
INSERT INTO Annee_Scolaire (Id_AnneeScolaire, Annee_Scolaire) VALUES  (24535, 'Metus imperdiet gravida nisl vel volutpat.');
INSERT INTO Annee_Scolaire (Id_AnneeScolaire, Annee_Scolaire) VALUES  (99640, 'Aptent vestibulum placerat nascetur pulvinar a risus.');
INSERT INTO Annee_Scolaire (Id_AnneeScolaire, Annee_Scolaire) VALUES  (24535, 'Vestibulum pharetra metus montes cubilia class arcu accumsan tellus.');
INSERT INTO Section (Id_Section, Nom_Section, Degres_Section, Nom_Titulaire) VALUES  (1161, 'Proin viverra pulvinar purus massa eu turpis posuere.', 'Etiam lectus hendrerit lorem et vel vitae accumsan.', 'Gravida porta lorem elementum sed facilisi augue malesuada elit.');
INSERT INTO Section (Id_Section, Nom_Section, Degres_Section, Nom_Titulaire) VALUES  (22578, 'Odio at justo taciti class tellus bibendum semper semper.', 'Nostra pretium quisque ornare vitae ut rhoncus.', 'Sociosqu erat quisque amet ultricies mauris.');
INSERT INTO Section (Id_Section, Nom_Section, Degres_Section, Nom_Titulaire) VALUES  (20165, 'Et auctor morbi mauris ultricies condimentum quam libero velit.', 'Sollicitudin consequat auctor vivamus posuere nonummy.', 'Mi placerat ultricies nam vivamus.');
INSERT INTO Section (Id_Section, Nom_Section, Degres_Section, Nom_Titulaire) VALUES  (1161, 'Torquent ullamcorper ullamcorper sociis justo nam morbi.', 'Placerat ipsum ut massa penatibus taciti faucibus vel suspendisse.', 'Interdum mollis maecenas risus lorem.');
INSERT INTO Section (Id_Section, Nom_Section, Degres_Section, Nom_Titulaire) VALUES  (54545, 'Id orci commodo neque netus dignissim.', 'Blandit eleifend torquent sapien et volutpat curabitur.', 'Cum pretium curae; ornare quisque suscipit ac luctus fusce.');
INSERT INTO Section (Id_Section, Nom_Section, Degres_Section, Nom_Titulaire) VALUES  (92864, 'Ridiculus aptent varius natoque accumsan gravida placerat leo.', 'Metus nostra mi risus fames duis.', 'Id metus lobortis ridiculus magna class aenean.');
INSERT INTO Section (Id_Section, Nom_Section, Degres_Section, Nom_Titulaire) VALUES  (99640, 'Vestibulum ullamcorper pellentesque netus ullamcorper sit ipsum nam.', 'Id tempus eu rutrum auctor accumsan sollicitudin egestas.', 'Augue blandit egestas sociis mauris aptent quis nonummy scelerisque.');
INSERT INTO Section (Id_Section, Nom_Section, Degres_Section, Nom_Titulaire) VALUES  (38072, 'Malesuada eleifend porttitor semper venenatis inceptos.', 'Magna magnis ac nam rhoncus dictum nisl lobortis.', 'Scelerisque cum hendrerit feugiat nec tincidunt.');
INSERT INTO Section (Id_Section, Nom_Section, Degres_Section, Nom_Titulaire) VALUES  (24535, 'Habitant sollicitudin egestas nam congue tristique diam dignissim.', 'Ridiculus nascetur mauris suscipit quisque eget suscipit.', 'Nullam suspendisse lacinia metus fusce cubilia posuere consequat magna.');
INSERT INTO Section (Id_Section, Nom_Section, Degres_Section, Nom_Titulaire) VALUES  (20165, 'Ligula auctor ad suspendisse et risus augue aptent.', 'Condimentum nam maecenas primis dis scelerisque justo pede.', 'Litora habitant inceptos tortor fringilla.');
INSERT INTO Section (Id_Section, Nom_Section, Degres_Section, Nom_Titulaire) VALUES  (99640, 'Ultrices nec bibendum praesent fermentum maecenas.', 'Suscipit purus cubilia magnis adipiscing.', 'Erat habitant venenatis scelerisque congue cubilia inceptos mi.');
INSERT INTO Section (Id_Section, Nom_Section, Degres_Section, Nom_Titulaire) VALUES  (45161, 'Vitae felis parturient fermentum parturient fermentum odio egestas dui.', 'Augue integer purus montes lobortis porttitor convallis mus.', 'Malesuada rutrum leo sollicitudin urna conubia sit.');
INSERT INTO Section (Id_Section, Nom_Section, Degres_Section, Nom_Titulaire) VALUES  (37243, 'Pulvinar enim aliquet lectus ante velit parturient interdum adipiscing.', 'Bibendum enim a enim elit magna.', 'Montes dolor interdum in proin.');
INSERT INTO Section (Id_Section, Nom_Section, Degres_Section, Nom_Titulaire) VALUES  (18645, 'Sodales varius dolor cursus eleifend pede.', 'Elit congue senectus sapien massa consequat consectetuer dui.', 'Venenatis non conubia senectus purus eros auctor neque penatibus.');
INSERT INTO Section (Id_Section, Nom_Section, Degres_Section, Nom_Titulaire) VALUES  (21155, 'Sodales dui mi vivamus habitant sapien ultricies et.', 'Phasellus blandit imperdiet nonummy varius tempor natoque dignissim eros.', 'A quis rutrum pede varius purus tristique eu porta.');
INSERT INTO Section (Id_Section, Nom_Section, Degres_Section, Nom_Titulaire) VALUES  (18645, 'Primis dui tincidunt sed iaculis lacinia viverra placerat mauris.', 'Nisi mus vitae eleifend erat nascetur aliquet.', 'Mollis hendrerit cursus ridiculus hendrerit lorem etiam volutpat conubia.');
INSERT INTO Section (Id_Section, Nom_Section, Degres_Section, Nom_Titulaire) VALUES  (92864, 'Ut ridiculus aliquet tincidunt fermentum varius.', 'Cubilia suscipit sollicitudin phasellus torquent lacus justo scelerisque.', 'Nonummy conubia sagittis neque molestie.');
INSERT INTO Section (Id_Section, Nom_Section, Degres_Section, Nom_Titulaire) VALUES  (38072, 'Dapibus nam est pede mattis morbi.', 'Sed justo ornare accumsan congue mi facilisi tincidunt.', 'Venenatis orci felis ornare fames neque venenatis congue orci.');
INSERT INTO Section (Id_Section, Nom_Section, Degres_Section, Nom_Titulaire) VALUES  (23753, 'Placerat pharetra feugiat nibh vestibulum commodo nibh ornare.', 'Elit adipiscing interdum ullamcorper ipsum est.', 'Molestie faucibus viverra volutpat aenean cubilia parturient.');
INSERT INTO Section (Id_Section, Nom_Section, Degres_Section, Nom_Titulaire) VALUES  (75038, 'Conubia ac orci donec blandit sociis tristique aenean.', 'Curae; ad nisi ullamcorper sed.', 'Pharetra vestibulum sociis elementum porta rutrum sit rutrum laoreet.');
