INSERT INTO drone (idDrone, brand, model, refDrone, state, speedMax, speedUnit, isDeleted) VALUES (SOON...);
INSERT INTO drone (idDrone, brand, model, refDrone, state, speedMax, speedUnit, isDeleted) VALUES (SOON...);
INSERT INTO drone (idDrone, brand, model, refDrone, state, speedMax, speedUnit, isDeleted) VALUES (SOON...);
INSERT INTO drone (idDrone, brand, model, refDrone, state, speedMax, speedUnit, isDeleted) VALUES (SOON...);
INSERT INTO drone (idDrone, brand, model, refDrone, state, speedMax, speedUnit, isDeleted) VALUES (SOON...);
INSERT INTO drone (idDrone, brand, model, refDrone, state, speedMax, speedUnit, isDeleted) VALUES (SOON...);
INSERT INTO drone (idDrone, brand, model, refDrone, state, speedMax, speedUnit, isDeleted) VALUES (SOON...);
INSERT INTO drone (idDrone, brand, model, refDrone, state, speedMax, speedUnit, isDeleted) VALUES (SOON...);
INSERT INTO drone (idDrone, brand, model, refDrone, state, speedMax, speedUnit, isDeleted) VALUES (SOON...);
INSERT INTO drone (idDrone, brand, model, refDrone, state, speedMax, speedUnit, isDeleted) VALUES (SOON...);
INSERT INTO catalogfood (idCatalogfood, name, description) VALUES (SOON...);
INSERT INTO catalogfood (idCatalogfood, name, description) VALUES (SOON...);
INSERT INTO catalogfood (idCatalogfood, name, description) VALUES (SOON...);
INSERT INTO catalogfood (idCatalogfood, name, description) VALUES (SOON...);
INSERT INTO catalogfood (idCatalogfood, name, description) VALUES (SOON...);
INSERT INTO catalogfood (idCatalogfood, name, description) VALUES (SOON...);
INSERT INTO catalogfood (idCatalogfood, name, description) VALUES (SOON...);
INSERT INTO catalogfood (idCatalogfood, name, description) VALUES (SOON...);
INSERT INTO catalogfood (idCatalogfood, name, description) VALUES (SOON...);
INSERT INTO catalogfood (idCatalogfood, name, description) VALUES (SOON...);
INSERT INTO product (idProduct, name, price, productType, pictureUrl, quantity, measureUnit, littleDescription, quantityStock, isDeleted, idCatalogfood) VALUES (SOON...);
INSERT INTO product (idProduct, name, price, productType, pictureUrl, quantity, measureUnit, littleDescription, quantityStock, isDeleted, idCatalogfood) VALUES (SOON...);
INSERT INTO product (idProduct, name, price, productType, pictureUrl, quantity, measureUnit, littleDescription, quantityStock, isDeleted, idCatalogfood) VALUES (SOON...);
INSERT INTO product (idProduct, name, price, productType, pictureUrl, quantity, measureUnit, littleDescription, quantityStock, isDeleted, idCatalogfood) VALUES (SOON...);
INSERT INTO product (idProduct, name, price, productType, pictureUrl, quantity, measureUnit, littleDescription, quantityStock, isDeleted, idCatalogfood) VALUES (SOON...);
INSERT INTO product (idProduct, name, price, productType, pictureUrl, quantity, measureUnit, littleDescription, quantityStock, isDeleted, idCatalogfood) VALUES (SOON...);
INSERT INTO product (idProduct, name, price, productType, pictureUrl, quantity, measureUnit, littleDescription, quantityStock, isDeleted, idCatalogfood) VALUES (SOON...);
INSERT INTO product (idProduct, name, price, productType, pictureUrl, quantity, measureUnit, littleDescription, quantityStock, isDeleted, idCatalogfood) VALUES (SOON...);
INSERT INTO product (idProduct, name, price, productType, pictureUrl, quantity, measureUnit, littleDescription, quantityStock, isDeleted, idCatalogfood) VALUES (SOON...);
INSERT INTO product (idProduct, name, price, productType, pictureUrl, quantity, measureUnit, littleDescription, quantityStock, isDeleted, idCatalogfood) VALUES (SOON...);
INSERT INTO address (idAddress, street, streetNumber, mailbox, postalCode, city, country) VALUES (SOON...);
INSERT INTO address (idAddress, street, streetNumber, mailbox, postalCode, city, country) VALUES (SOON...);
INSERT INTO address (idAddress, street, streetNumber, mailbox, postalCode, city, country) VALUES (SOON...);
INSERT INTO address (idAddress, street, streetNumber, mailbox, postalCode, city, country) VALUES (SOON...);
INSERT INTO address (idAddress, street, streetNumber, mailbox, postalCode, city, country) VALUES (SOON...);
INSERT INTO address (idAddress, street, streetNumber, mailbox, postalCode, city, country) VALUES (SOON...);
INSERT INTO address (idAddress, street, streetNumber, mailbox, postalCode, city, country) VALUES (SOON...);
INSERT INTO address (idAddress, street, streetNumber, mailbox, postalCode, city, country) VALUES (SOON...);
INSERT INTO address (idAddress, street, streetNumber, mailbox, postalCode, city, country) VALUES (SOON...);
INSERT INTO address (idAddress, street, streetNumber, mailbox, postalCode, city, country) VALUES (SOON...);
INSERT INTO society (idSociety, name, vatNumber, dateOfCreation, pictureUrl, label, idCatalogfood, idAddress) VALUES (SOON...);
INSERT INTO society (idSociety, name, vatNumber, dateOfCreation, pictureUrl, label, idCatalogfood, idAddress) VALUES (SOON...);
INSERT INTO society (idSociety, name, vatNumber, dateOfCreation, pictureUrl, label, idCatalogfood, idAddress) VALUES (SOON...);
INSERT INTO society (idSociety, name, vatNumber, dateOfCreation, pictureUrl, label, idCatalogfood, idAddress) VALUES (SOON...);
INSERT INTO society (idSociety, name, vatNumber, dateOfCreation, pictureUrl, label, idCatalogfood, idAddress) VALUES (SOON...);
INSERT INTO society (idSociety, name, vatNumber, dateOfCreation, pictureUrl, label, idCatalogfood, idAddress) VALUES (SOON...);
INSERT INTO society (idSociety, name, vatNumber, dateOfCreation, pictureUrl, label, idCatalogfood, idAddress) VALUES (SOON...);
INSERT INTO society (idSociety, name, vatNumber, dateOfCreation, pictureUrl, label, idCatalogfood, idAddress) VALUES (SOON...);
INSERT INTO society (idSociety, name, vatNumber, dateOfCreation, pictureUrl, label, idCatalogfood, idAddress) VALUES (SOON...);
INSERT INTO society (idSociety, name, vatNumber, dateOfCreation, pictureUrl, label, idCatalogfood, idAddress) VALUES (SOON...);
INSERT INTO orderfood (idOrderfood, reference, date, amount, state, shipStart, shipEnd, isDeleted, idDrone, idAddress) VALUES (SOON...);
INSERT INTO orderfood (idOrderfood, reference, date, amount, state, shipStart, shipEnd, isDeleted, idDrone, idAddress) VALUES (SOON...);
INSERT INTO orderfood (idOrderfood, reference, date, amount, state, shipStart, shipEnd, isDeleted, idDrone, idAddress) VALUES (SOON...);
INSERT INTO orderfood (idOrderfood, reference, date, amount, state, shipStart, shipEnd, isDeleted, idDrone, idAddress) VALUES (SOON...);
INSERT INTO orderfood (idOrderfood, reference, date, amount, state, shipStart, shipEnd, isDeleted, idDrone, idAddress) VALUES (SOON...);
INSERT INTO orderfood (idOrderfood, reference, date, amount, state, shipStart, shipEnd, isDeleted, idDrone, idAddress) VALUES (SOON...);
INSERT INTO orderfood (idOrderfood, reference, date, amount, state, shipStart, shipEnd, isDeleted, idDrone, idAddress) VALUES (SOON...);
INSERT INTO orderfood (idOrderfood, reference, date, amount, state, shipStart, shipEnd, isDeleted, idDrone, idAddress) VALUES (SOON...);
INSERT INTO orderfood (idOrderfood, reference, date, amount, state, shipStart, shipEnd, isDeleted, idDrone, idAddress) VALUES (SOON...);
INSERT INTO orderfood (idOrderfood, reference, date, amount, state, shipStart, shipEnd, isDeleted, idDrone, idAddress) VALUES (SOON...);
INSERT INTO user (idUser, firstname, lastname, birthdate, gender, usertype, avatarUrl, username, email, password, authcode, isDeleted, idSociety) VALUES (SOON...);
INSERT INTO user (idUser, firstname, lastname, birthdate, gender, usertype, avatarUrl, username, email, password, authcode, isDeleted, idSociety) VALUES (SOON...);
INSERT INTO user (idUser, firstname, lastname, birthdate, gender, usertype, avatarUrl, username, email, password, authcode, isDeleted, idSociety) VALUES (SOON...);
INSERT INTO user (idUser, firstname, lastname, birthdate, gender, usertype, avatarUrl, username, email, password, authcode, isDeleted, idSociety) VALUES (SOON...);
INSERT INTO user (idUser, firstname, lastname, birthdate, gender, usertype, avatarUrl, username, email, password, authcode, isDeleted, idSociety) VALUES (SOON...);
INSERT INTO user (idUser, firstname, lastname, birthdate, gender, usertype, avatarUrl, username, email, password, authcode, isDeleted, idSociety) VALUES (SOON...);
INSERT INTO user (idUser, firstname, lastname, birthdate, gender, usertype, avatarUrl, username, email, password, authcode, isDeleted, idSociety) VALUES (SOON...);
INSERT INTO user (idUser, firstname, lastname, birthdate, gender, usertype, avatarUrl, username, email, password, authcode, isDeleted, idSociety) VALUES (SOON...);
INSERT INTO user (idUser, firstname, lastname, birthdate, gender, usertype, avatarUrl, username, email, password, authcode, isDeleted, idSociety) VALUES (SOON...);
INSERT INTO user (idUser, firstname, lastname, birthdate, gender, usertype, avatarUrl, username, email, password, authcode, isDeleted, idSociety) VALUES (SOON...);
INSERT INTO menu (idMenu, name, price, pictureUrl, littleDescription, isDeleted, idCatalogfood) VALUES (SOON...);
INSERT INTO menu (idMenu, name, price, pictureUrl, littleDescription, isDeleted, idCatalogfood) VALUES (SOON...);
INSERT INTO menu (idMenu, name, price, pictureUrl, littleDescription, isDeleted, idCatalogfood) VALUES (SOON...);
INSERT INTO menu (idMenu, name, price, pictureUrl, littleDescription, isDeleted, idCatalogfood) VALUES (SOON...);
INSERT INTO menu (idMenu, name, price, pictureUrl, littleDescription, isDeleted, idCatalogfood) VALUES (SOON...);
INSERT INTO menu (idMenu, name, price, pictureUrl, littleDescription, isDeleted, idCatalogfood) VALUES (SOON...);
INSERT INTO menu (idMenu, name, price, pictureUrl, littleDescription, isDeleted, idCatalogfood) VALUES (SOON...);
INSERT INTO menu (idMenu, name, price, pictureUrl, littleDescription, isDeleted, idCatalogfood) VALUES (SOON...);
INSERT INTO menu (idMenu, name, price, pictureUrl, littleDescription, isDeleted, idCatalogfood) VALUES (SOON...);
INSERT INTO menu (idMenu, name, price, pictureUrl, littleDescription, isDeleted, idCatalogfood) VALUES (SOON...);
INSERT INTO orderfood_product (idProduct, idOrderfood, quantity) VALUES (SOON...);
INSERT INTO orderfood_product (idProduct, idOrderfood, quantity) VALUES (SOON...);
INSERT INTO orderfood_product (idProduct, idOrderfood, quantity) VALUES (SOON...);
INSERT INTO orderfood_product (idProduct, idOrderfood, quantity) VALUES (SOON...);
INSERT INTO orderfood_product (idProduct, idOrderfood, quantity) VALUES (SOON...);
INSERT INTO orderfood_product (idProduct, idOrderfood, quantity) VALUES (SOON...);
INSERT INTO orderfood_product (idProduct, idOrderfood, quantity) VALUES (SOON...);
INSERT INTO orderfood_product (idProduct, idOrderfood, quantity) VALUES (SOON...);
INSERT INTO orderfood_product (idProduct, idOrderfood, quantity) VALUES (SOON...);
INSERT INTO orderfood_product (idProduct, idOrderfood, quantity) VALUES (SOON...);
INSERT INTO user_address (idUser, idAddress, label) VALUES (SOON...);
INSERT INTO user_address (idUser, idAddress, label) VALUES (SOON...);
INSERT INTO user_address (idUser, idAddress, label) VALUES (SOON...);
INSERT INTO user_address (idUser, idAddress, label) VALUES (SOON...);
INSERT INTO user_address (idUser, idAddress, label) VALUES (SOON...);
INSERT INTO user_address (idUser, idAddress, label) VALUES (SOON...);
INSERT INTO user_address (idUser, idAddress, label) VALUES (SOON...);
INSERT INTO user_address (idUser, idAddress, label) VALUES (SOON...);
INSERT INTO user_address (idUser, idAddress, label) VALUES (SOON...);
INSERT INTO user_address (idUser, idAddress, label) VALUES (SOON...);
INSERT INTO product_menu (idMenu, idProduct, quantity) VALUES (SOON...);
INSERT INTO product_menu (idMenu, idProduct, quantity) VALUES (SOON...);
INSERT INTO product_menu (idMenu, idProduct, quantity) VALUES (SOON...);
INSERT INTO product_menu (idMenu, idProduct, quantity) VALUES (SOON...);
INSERT INTO product_menu (idMenu, idProduct, quantity) VALUES (SOON...);
INSERT INTO product_menu (idMenu, idProduct, quantity) VALUES (SOON...);
INSERT INTO product_menu (idMenu, idProduct, quantity) VALUES (SOON...);
INSERT INTO product_menu (idMenu, idProduct, quantity) VALUES (SOON...);
INSERT INTO product_menu (idMenu, idProduct, quantity) VALUES (SOON...);
INSERT INTO product_menu (idMenu, idProduct, quantity) VALUES (SOON...);
INSERT INTO handle_order (idOrderfood, idUser, idUserOrdered) VALUES (SOON...);
INSERT INTO handle_order (idOrderfood, idUser, idUserOrdered) VALUES (SOON...);
INSERT INTO handle_order (idOrderfood, idUser, idUserOrdered) VALUES (SOON...);
INSERT INTO handle_order (idOrderfood, idUser, idUserOrdered) VALUES (SOON...);
INSERT INTO handle_order (idOrderfood, idUser, idUserOrdered) VALUES (SOON...);
INSERT INTO handle_order (idOrderfood, idUser, idUserOrdered) VALUES (SOON...);
INSERT INTO handle_order (idOrderfood, idUser, idUserOrdered) VALUES (SOON...);
INSERT INTO handle_order (idOrderfood, idUser, idUserOrdered) VALUES (SOON...);
INSERT INTO handle_order (idOrderfood, idUser, idUserOrdered) VALUES (SOON...);
INSERT INTO handle_order (idOrderfood, idUser, idUserOrdered) VALUES (SOON...);
INSERT INTO order_menu (idMenu, idOrderfood, quantity) VALUES (SOON...);
INSERT INTO order_menu (idMenu, idOrderfood, quantity) VALUES (SOON...);
INSERT INTO order_menu (idMenu, idOrderfood, quantity) VALUES (SOON...);
INSERT INTO order_menu (idMenu, idOrderfood, quantity) VALUES (SOON...);
INSERT INTO order_menu (idMenu, idOrderfood, quantity) VALUES (SOON...);
INSERT INTO order_menu (idMenu, idOrderfood, quantity) VALUES (SOON...);
INSERT INTO order_menu (idMenu, idOrderfood, quantity) VALUES (SOON...);
INSERT INTO order_menu (idMenu, idOrderfood, quantity) VALUES (SOON...);
INSERT INTO order_menu (idMenu, idOrderfood, quantity) VALUES (SOON...);
INSERT INTO order_menu (idMenu, idOrderfood, quantity) VALUES (SOON...);
